name: terraform setup
on: 
  push: 
    branches:
      - main
  workflow_dispatch:
jobs:
  terraform_init:
    name: Terraform Init
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: terrform setup
        uses: hashicorp/setup-terraform@v2.0.3
      - name: Terraform Init
        working-directory: environment/dev
        run: terraform init
         
